/ich/Programmieren/KazadeEngine/NeHeKazmath/kazmath/src/mat3.c File Reference
#include <stdlib.h>
#include <memory.h>
#include <assert.h>
#include `utility.h`
#include `vec3.h`
#include `mat3.h`
#include `quaternion.h`
Functions
kmMat3 * kmMat3Fill (kmMat3 *pOut, const kmScalar *pMat)
kmMat3 * kmMat3Identity (kmMat3 *pOut)
kmScalar kmMat3Determinant (const kmMat3 *pIn)
kmMat3 * kmMat3Adjugate (kmMat3 *pOut, const kmMat3 *pIn)
kmMat3 * kmMat3Inverse (kmMat3 *pOut, const kmScalar pDeterminate, const kmMat3 *pM)
int kmMat3IsIdentity (const kmMat3 *pIn)
kmMat3 * kmMat3Transpose (kmMat3 *pOut, const kmMat3 *pIn)
kmMat3 * kmMat3Multiply (kmMat3 *pOut, const kmMat3 *pM1, const kmMat3 *pM2)
kmMat3 * kmMat3ScalarMultiply (kmMat3 *pOut, const kmMat3 *pM, const kmScalar pFactor)
kmMat3 * kmMat3Assign (kmMat3 *pOut, const kmMat3 *pIn)
int kmMat3AreEqual (const kmMat3 *pMat1, const kmMat3 *pMat2)
kmMat3 * kmMat3Rotation (kmMat3 *pOut, const float radians)
kmMat3 * kmMat3Scaling (kmMat3 *pOut, const kmScalar x, const kmScalar y)
kmMat3 * kmMat3Translation (kmMat3 *pOut, const kmScalar x, const kmScalar y)
Function Documentation
kmMat3* kmMat3Adjugate (kmMat3 * pOut, const kmMat3 * pIn)
Definition at line 68 of file mat3.c.
References kmMat3::mat.
Referenced by kmMat3Inverse().
int kmMat3AreEqual (const kmMat3 * pMat1, const kmMat3 * pMat2)
Returns true if the 2 matrices are equal (approximately)
Definition at line 174 of file mat3.c.
References KM_FALSE, kmEpsilon, and kmMat3::mat.
kmMat3* kmMat3Assign (kmMat3 * pOut, const kmMat3 * pIn)
Assigns the value of pIn to pOut
Definition at line 164 of file mat3.c.
References kmMat3::mat.
kmScalar kmMat3Determinant (const kmMat3 * pIn)
Definition at line 49 of file mat3.c.
References kmScalar, and kmMat3::mat.
kmMat3* kmMat3Fill (kmMat3 * pOut, const kmScalar * pMat)
Definition at line 35 of file mat3.c.
References kmScalar, and kmMat3::mat.
kmMat3* kmMat3Identity (kmMat3 * pOut)
Sets pOut to an identity matrix returns pOut
Definition at line 42 of file mat3.c.
References kmMat3::mat.
kmMat3* kmMat3Inverse (kmMat3 * pOut, const kmScalar pDeterminate, const kmMat3 * pM)
Definition at line 83 of file mat3.c.
References kmMat3Adjugate(), kmMat3ScalarMultiply(), and kmScalar.
int kmMat3IsIdentity (const kmMat3 * pIn)
Returns true if pIn is an identity matrix
Definition at line 102 of file mat3.c.
References kmMat3::mat.
kmMat3* kmMat3Multiply (kmMat3 * pOut, const kmMat3 * pM1, const kmMat3 * pM2)
Definition at line 125 of file mat3.c.
References kmMat3::mat.
kmMat3* kmMat3Rotation (kmMat3 * pOut, const float radians)
Definition at line 190 of file mat3.c.
References kmMat3::mat.
kmMat3* kmMat3ScalarMultiply (kmMat3 * pOut, const kmMat3 * pM, const kmScalar pFactor)
Definition at line 148 of file mat3.c.
References kmMat3::mat.
Referenced by kmMat3Inverse().
kmMat3* kmMat3Scaling (kmMat3 * pOut, const kmScalar x, const kmScalar y)
Builds a scaling matrix
Definition at line 214 of file mat3.c.
References kmMat3::mat.
kmMat3* kmMat3Translation (kmMat3 * pOut, const kmScalar x, const kmScalar y)
Definition at line 224 of file mat3.c.
References kmMat3::mat.
kmMat3* kmMat3Transpose (kmMat3 * pOut, const kmMat3 * pIn)
Sets pOut to the transpose of pIn, returns pOut
Definition at line 112 of file mat3.c.
References kmMat3::mat.