/ich/Programmieren/KazadeEngine/NeHeKazmath/kazmath/src/utility.c File Reference
#include `utility.h`
Functions
kmScalar kmSQR (kmScalar s)
kmScalar kmDegreesToRadians (kmScalar degrees)
kmScalar kmRadiansToDegrees (kmScalar radians)
Function Documentation
kmScalar kmDegreesToRadians (kmScalar degrees)
Returns degrees as radians.
Definition at line 38 of file utility.c.
References kmPIOver180.
Referenced by kmGLRotatef(), kmMat4PerspectiveProjection(), and kmQuaternionRotationYawPitchRoll().
kmScalar kmRadiansToDegrees (kmScalar radians)
Returns radians as degrees
Definition at line 45 of file utility.c.
References kmPIUnder180.
kmScalar kmSQR (kmScalar s)
Returns the square of s (e.g. s*s)
Definition at line 31 of file utility.c.
Referenced by kmQuaternionSlerp(), kmQuaternionToAxisAngle(), kmVec2Length(), kmVec2LengthSq(), kmVec3Length(), kmVec3LengthSq(), kmVec4Length(), and kmVec4LengthSq().