/ich/Programmieren/KazadeEngine/NeHeKazmath/kazmath/src/GL/mat4stack.c File Reference
#include <malloc.h>
#include <memory.h>
#include <assert.h>
#include <stdio.h>
#include `mat4stack.h`
Defines
#define INITIAL_SIZE 30
#define INCREMENT 50
Functions
void km_mat4_stack_initialize (km_mat4_stack *stack)
void km_mat4_stack_push (km_mat4_stack *stack, const kmMat4 *item)
void km_mat4_stack_pop (km_mat4_stack *stack, kmMat4 *pOut)
void km_mat4_stack_release (km_mat4_stack *stack)
Define Documentation
#define INCREMENT 50
Definition at line 32 of file mat4stack.c.
Referenced by km_mat4_stack_push().
#define INITIAL_SIZE 30
Definition at line 31 of file mat4stack.c.
Referenced by km_mat4_stack_initialize().
Function Documentation
void km_mat4_stack_initialize (km_mat4_stack * stack)
Definition at line 36 of file mat4stack.c.
References km_mat4_stack::capacity, INITIAL_SIZE, km_mat4_stack::item_count, km_mat4_stack::stack, and km_mat4_stack::top.
Referenced by lazyInitialize().
void km_mat4_stack_pop (km_mat4_stack * stack, kmMat4 * pOut)
Definition at line 62 of file mat4stack.c.
References km_mat4_stack::item_count, km_mat4_stack::stack, and km_mat4_stack::top.
Referenced by kmGLPopMatrix().
void km_mat4_stack_push (km_mat4_stack * stack, const kmMat4 * item)
Definition at line 43 of file mat4stack.c.
References km_mat4_stack::capacity, INCREMENT, km_mat4_stack::item_count, km_mat4_stack::stack, and km_mat4_stack::top.
Referenced by kmGLPushMatrix(), and lazyInitialize().
void km_mat4_stack_release (km_mat4_stack * stack)
Definition at line 75 of file mat4stack.c.
References km_mat4_stack::capacity, km_mat4_stack::item_count, km_mat4_stack::stack, and km_mat4_stack::top.
Referenced by kmGLFreeAll().