/ich/Programmieren/KazadeEngine/NeHeKazmath/kazmath/src/GL/matrix.h File Reference
#include `../mat4.h`
#include `../vec3.h`
Defines
#define KM_GL_MODELVIEW 0x1700
#define KM_GL_PROJECTION 0x1701
#define KM_GL_TEXTURE 0x1702
Typedefs
typedef unsigned int kmGLEnum
Functions
void kmGLPushMatrix (void)
void kmGLPopMatrix (void)
void kmGLMatrixMode (kmGLEnum mode)
void kmGLLoadIdentity (void)
void kmGLLoadMatrix (const kmMat4 *pIn)
void kmGLMultMatrix (const kmMat4 *pIn)
void kmGLTranslatef (float x, float y, float z)
void kmGLRotatef (float angle, float x, float y, float z)
void kmGLScalef (float x, float y, float z)
void kmGLGetMatrix (kmGLEnum mode, kmMat4 *pOut)
Define Documentation
#define KM_GL_MODELVIEW 0x1700
Definition at line 29 of file matrix.h.
Referenced by kmGLGetMatrix(), and kmGLMatrixMode().
#define KM_GL_PROJECTION 0x1701
Definition at line 30 of file matrix.h.
Referenced by kmGLGetMatrix(), and kmGLMatrixMode().
#define KM_GL_TEXTURE 0x1702
Definition at line 31 of file matrix.h.
Referenced by kmGLGetMatrix(), and kmGLMatrixMode().
Typedef Documentation
typedef unsigned int kmGLEnum
Definition at line 33 of file matrix.h.
Function Documentation
void kmGLGetMatrix (kmGLEnum mode, kmMat4 * pOut)
Definition at line 132 of file matrix.c.
References KM_GL_MODELVIEW, KM_GL_PROJECTION, KM_GL_TEXTURE, kmMat4Assign(), lazyInitialize(), and km_mat4_stack::top.
void kmGLLoadIdentity (void)
Definition at line 102 of file matrix.c.
References kmMat4Identity(), lazyInitialize(), and km_mat4_stack::top.
void kmGLLoadMatrix (const kmMat4 * pIn)
void kmGLMatrixMode (kmGLEnum mode)
Definition at line 67 of file matrix.c.
References KM_GL_MODELVIEW, KM_GL_PROJECTION, KM_GL_TEXTURE, and lazyInitialize().
void kmGLMultMatrix (const kmMat4 * pIn)
Definition at line 126 of file matrix.c.
References kmMat4Multiply(), lazyInitialize(), and km_mat4_stack::top.
void kmGLPopMatrix (void)
Definition at line 96 of file matrix.c.
References km_mat4_stack_pop().
void kmGLPushMatrix (void)
Definition at line 88 of file matrix.c.
References km_mat4_stack_push(), lazyInitialize(), and km_mat4_stack::top.
void kmGLRotatef (float angle, float x, float y, float z)
Definition at line 160 of file matrix.c.
References kmDegreesToRadians(), kmMat4Multiply(), kmMat4RotationAxis(), kmVec3Fill(), and km_mat4_stack::top.
void kmGLScalef (float x, float y, float z)
Definition at line 175 of file matrix.c.
References kmMat4Multiply(), kmMat4Scaling(), and km_mat4_stack::top.
void kmGLTranslatef (float x, float y, float z)
Definition at line 153 of file matrix.c.
References kmMat4::mat, and km_mat4_stack::top.