/ich/Programmieren/KazadeEngine/NeHeKazmath/kazmath/src/GL/matrix.c File Reference
#include <stdlib.h>
#include <assert.h>
#include `matrix.h`
#include `mat4stack.h`
Functions
void lazyInitialize ()
void kmGLMatrixMode (kmGLEnum mode)
void kmGLPushMatrix (void)
void kmGLPopMatrix (void)
void kmGLLoadIdentity ()
void kmGLFreeAll ()
void kmGLMultMatrix (const kmMat4 *pIn)
void kmGLGetMatrix (kmGLEnum mode, kmMat4 *pOut)
void kmGLTranslatef (float x, float y, float z)
void kmGLRotatef (float angle, float x, float y, float z)
void kmGLScalef (float x, float y, float z)
Variables
km_mat4_stack * modelview_matrix_stack = NULL
km_mat4_stack * projection_matrix_stack = NULL
km_mat4_stack * texture_matrix_stack = NULL
km_mat4_stack * current_stack = NULL
Function Documentation
void kmGLFreeAll ()
Definition at line 109 of file matrix.c.
References km_mat4_stack_release().
void kmGLGetMatrix (kmGLEnum mode, kmMat4 * pOut)
Definition at line 132 of file matrix.c.
References KM_GL_MODELVIEW, KM_GL_PROJECTION, KM_GL_TEXTURE, kmMat4Assign(), lazyInitialize(), and km_mat4_stack::top.
void kmGLLoadIdentity (void)
Definition at line 102 of file matrix.c.
References kmMat4Identity(), lazyInitialize(), and km_mat4_stack::top.
void kmGLMatrixMode (kmGLEnum mode)
Definition at line 67 of file matrix.c.
References KM_GL_MODELVIEW, KM_GL_PROJECTION, KM_GL_TEXTURE, and lazyInitialize().
void kmGLMultMatrix (const kmMat4 * pIn)
Definition at line 126 of file matrix.c.
References kmMat4Multiply(), lazyInitialize(), and km_mat4_stack::top.
void kmGLPopMatrix (void)
Definition at line 96 of file matrix.c.
References km_mat4_stack_pop().
void kmGLPushMatrix (void)
Definition at line 88 of file matrix.c.
References km_mat4_stack_push(), lazyInitialize(), and km_mat4_stack::top.
void kmGLRotatef (float angle, float x, float y, float z)
Definition at line 160 of file matrix.c.
References kmDegreesToRadians(), kmMat4Multiply(), kmMat4RotationAxis(), kmVec3Fill(), and km_mat4_stack::top.
void kmGLScalef (float x, float y, float z)
Definition at line 175 of file matrix.c.
References kmMat4Multiply(), kmMat4Scaling(), and km_mat4_stack::top.
void kmGLTranslatef (float x, float y, float z)
Definition at line 153 of file matrix.c.
References kmMat4::mat, and km_mat4_stack::top.
void lazyInitialize ()
Definition at line 40 of file matrix.c.
References km_mat4_stack_initialize(), km_mat4_stack_push(), and kmMat4Identity().
Referenced by kmGLGetMatrix(), kmGLLoadIdentity(), kmGLMatrixMode(), kmGLMultMatrix(), and kmGLPushMatrix().
Variable Documentation
km_mat4_stack* current_stack = NULL
Definition at line 36 of file matrix.c.
km_mat4_stack* modelview_matrix_stack = NULL
Definition at line 32 of file matrix.c.
km_mat4_stack* projection_matrix_stack = NULL
Definition at line 33 of file matrix.c.
km_mat4_stack* texture_matrix_stack = NULL
Definition at line 34 of file matrix.c.