/ich/Programmieren/KazadeEngine/NeHeKazmath/kazmath/src/vec2.h File Reference
Data Structures
struct kmVec2
Defines
#define kmScalar float
Functions
kmVec2 * kmVec2Fill (kmVec2 *pOut, kmScalar x, kmScalar y)
kmScalar kmVec2Length (const kmVec2 *pIn)
Returns the length of the vector.
kmScalar kmVec2LengthSq (const kmVec2 *pIn)
Returns the square of the length of the vector.
kmVec2 * kmVec2Normalize (kmVec2 *pOut, const kmVec2 *pIn)
Returns the vector passed in set to unit length.
kmVec2 * kmVec2Add (kmVec2 *pOut, const kmVec2 *pV1, const kmVec2 *pV2)
Adds 2 vectors and returns the result.
kmScalar kmVec2Dot (const kmVec2 *pV1, const kmVec2 *pV2)
kmVec2 * kmVec2Subtract (kmVec2 *pOut, const kmVec2 *pV1, const kmVec2 *pV2)
Subtracts 2 vectors and returns the result.
kmVec2 * kmVec2Transform (kmVec2 *pOut, const kmVec2 *pV1, const struct kmMat4 *pM)
kmVec2 * kmVec2TransformCoord (kmVec2 *pOut, const kmVec2 *pV, const struct kmMat4 *pM)
Transforms a 3D vector by a given matrix, projecting the result back into w = 1.
kmVec2 * kmVec2Scale (kmVec2 *pOut, const kmVec2 *pIn, const kmScalar s)
Scales a vector to length s.
int kmVec2AreEqual (const kmVec2 *p1, const kmVec2 *p2)
Returns 1 if both vectors are equal.
Define Documentation
#define kmScalar float
Definition at line 32 of file vec2.h.
Function Documentation
kmVec2* kmVec2Add (kmVec2 * pOut, const kmVec2 * pV1, const kmVec2 * pV2)
Adds 2 vectors and returns the result.
Definition at line 60 of file vec2.c.
References kmVec2::x, and kmVec2::y.
int kmVec2AreEqual (const kmVec2 * p1, const kmVec2 * p2)
Returns 1 if both vectors are equal.
Definition at line 101 of file vec2.c.
References kmEpsilon, kmVec2::x, and kmVec2::y.
kmScalar kmVec2Dot (const kmVec2 * pV1, const kmVec2 * pV2)
Definition at line 68 of file vec2.c.
References kmVec2::x, and kmVec2::y.
kmVec2* kmVec2Fill (kmVec2 * pOut, kmScalar x, kmScalar y)
Definition at line 33 of file vec2.c.
References kmVec2::x, and kmVec2::y.
Referenced by kazmathxx::Vec2::operator*(), kazmathxx::Vec2::operator+(), kazmathxx::Vec2::operator-(), and kazmathxx::Vec2::operator/().
kmScalar kmVec2Length (const kmVec2 * pIn)
Returns the length of the vector.
Definition at line 40 of file vec2.c.
References kmSQR(), kmVec2::x, and kmVec2::y.
Referenced by kmVec2Normalize().
kmScalar kmVec2LengthSq (const kmVec2 * pIn)
Returns the square of the length of the vector.
Definition at line 45 of file vec2.c.
References kmSQR(), kmVec2::x, and kmVec2::y.
kmVec2* kmVec2Normalize (kmVec2 * pOut, const kmVec2 * pIn)
Returns the vector passed in set to unit length.
Definition at line 50 of file vec2.c.
References kmScalar, kmVec2Length(), kmVec2::x, and kmVec2::y.
kmVec2* kmVec2Scale (kmVec2 * pOut, const kmVec2 * pIn, const kmScalar s)
Scales a vector to length s.
Definition at line 93 of file vec2.c.
References kmVec2::x, and kmVec2::y.
kmVec2* kmVec2Subtract (kmVec2 * pOut, const kmVec2 * pV1, const kmVec2 * pV2)
Subtracts 2 vectors and returns the result.
Returns the Dot product which is the cosine of the angle between the two vectors multiplied by their lengths
Definition at line 73 of file vec2.c.
References kmVec2::x, and kmVec2::y.
kmVec2* kmVec2Transform (kmVec2 * pOut, const kmVec2 * pV1, const struct kmMat4 * pM)
kmVec2* kmVec2TransformCoord (kmVec2 * pOut, const kmVec2 * pV, const struct kmMat4 * pM)
Transforms a 3D vector by a given matrix, projecting the result back into w = 1.
Transform the Vector