//===========================================================================
//	AquaSonic	version 0.0
//
//
//	Made with doktor's BotStudio v. 0.98
//	http://www.planetquake.com/botstudio  e-mail: doktor@cutey.com
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"AquaSonic"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.2
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/aquasonic_w.c"
	CHARACTERISTIC_AIM_SKILL					0.6
	CHARACTERISTIC_AIM_ACCURACY					0.4
	CHARACTERISTIC_VIEW_FACTOR					0.4
	CHARACTERISTIC_VIEW_MAXCHANGE				120
	CHARACTERISTIC_REACTIONTIME					1.75

	CHARACTERISTIC_CHAT_FILE					"bots/aquasonic_t.c"
	CHARACTERISTIC_CHAT_NAME					"aquasonic"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					1.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.3
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.45
	CHARACTERISTIC_CHAT_KILL					0.05
	CHARACTERISTIC_CHAT_DEATH					0.85
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.35
	CHARACTERISTIC_CHAT_HITNODEATH				0.3
	CHARACTERISTIC_CHAT_HITNOKILL				0.55
	CHARACTERISTIC_CHAT_RANDOM					0.7
	CHARACTERISTIC_CHAT_REPLY					1.0

	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.05
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.45

	CHARACTERISTIC_ITEMWEIGHTS					"bots/aquasonic_i.c"
	CHARACTERISTIC_AGGRESSION					0.7
	CHARACTERISTIC_SELFPRESERVATION				0.35
	CHARACTERISTIC_VENGEFULNESS					0.4
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					0.1
	CHARACTERISTIC_ALERTNESS					0.2

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.4
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.7
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.1
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.1
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.3
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.15
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.3
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.1
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.1

	CHARACTERISTIC_FIRETHROTTLE					0.4
}

skill 4
{
	CHARACTERISTIC_NAME							"AquaSonic"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.7
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/aquasonic_w.c"
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_ACCURACY					0.4
	CHARACTERISTIC_VIEW_FACTOR					0.4
	CHARACTERISTIC_VIEW_MAXCHANGE				120
	CHARACTERISTIC_REACTIONTIME					1.5

	CHARACTERISTIC_CHAT_FILE					"bots/aquasonic_t.c"
	CHARACTERISTIC_CHAT_NAME					"aquasonic"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					1.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.3
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.45
	CHARACTERISTIC_CHAT_KILL					0.05
	CHARACTERISTIC_CHAT_DEATH					0.85
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.35
	CHARACTERISTIC_CHAT_HITNODEATH				0.3
	CHARACTERISTIC_CHAT_HITNOKILL				0.55
	CHARACTERISTIC_CHAT_RANDOM					0.7
	CHARACTERISTIC_CHAT_REPLY					1.0

	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.05
	CHARACTERISTIC_WEAPONJUMPING				0.05
	CHARACTERISTIC_GRAPPLE_USER					0.45

	CHARACTERISTIC_ITEMWEIGHTS					"bots/aquasonic_i.c"
	CHARACTERISTIC_AGGRESSION					0.7
	CHARACTERISTIC_SELFPRESERVATION				0.35
	CHARACTERISTIC_VENGEFULNESS					0.4
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					0.1
	CHARACTERISTIC_ALERTNESS					0.75

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.4
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.15
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.7
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.1
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.1
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.35
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.15
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.3
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.1
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.1
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.1

	CHARACTERISTIC_FIRETHROTTLE					0.45
}

skill 5
{
	CHARACTERISTIC_NAME							"AquaSonic"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.8
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/aquasonic_w.c"
	CHARACTERISTIC_AIM_SKILL					0.9
	CHARACTERISTIC_AIM_ACCURACY					0.4
	CHARACTERISTIC_VIEW_FACTOR					0.4
	CHARACTERISTIC_VIEW_MAXCHANGE				120
	CHARACTERISTIC_REACTIONTIME					1.5

	CHARACTERISTIC_CHAT_FILE					"bots/aquasonic_t.c"
	CHARACTERISTIC_CHAT_NAME					"aquasonic"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					1.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.3
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.45
	CHARACTERISTIC_CHAT_KILL					0.05
	CHARACTERISTIC_CHAT_DEATH					0.85
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.35
	CHARACTERISTIC_CHAT_HITNODEATH				0.3
	CHARACTERISTIC_CHAT_HITNOKILL				0.55
	CHARACTERISTIC_CHAT_RANDOM					0.7
	CHARACTERISTIC_CHAT_REPLY					1.0

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.05
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.45

	CHARACTERISTIC_ITEMWEIGHTS					"bots/aquasonic_i.c"
	CHARACTERISTIC_AGGRESSION					0.7
	CHARACTERISTIC_SELFPRESERVATION				0.35
	CHARACTERISTIC_VENGEFULNESS					0.4
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					0.1
	CHARACTERISTIC_ALERTNESS					0.8

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.4
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.15
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.7
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.1
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.1
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.35
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.15
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.3
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.1
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.1
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.1

	CHARACTERISTIC_FIRETHROTTLE					0.45
}
