//===========================================================================
//	BionicSonic	version 0.0
//
//
//	Made with doktor's BotStudio v. 0.98
//	http://www.planetquake.com/botstudio  e-mail: doktor@cutey.com
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"BionicSonic"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.5
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/bionicsonic_w.c"
	CHARACTERISTIC_AIM_SKILL					0.5
	CHARACTERISTIC_AIM_ACCURACY					0.5
	CHARACTERISTIC_VIEW_FACTOR					0.5
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					2

	CHARACTERISTIC_CHAT_FILE					"bots/bionicsonic_t.c"
	CHARACTERISTIC_CHAT_NAME					"bionicsonic"
	CHARACTERISTIC_CHAT_CPM						200
	CHARACTERISTIC_CHAT_INSULT					0.5
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.5
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.5

	CHARACTERISTIC_CROUCHER						0.2
	CHARACTERISTIC_JUMPER						0.4
	CHARACTERISTIC_WEAPONJUMPING				0.25
	CHARACTERISTIC_GRAPPLE_USER					0.5

	CHARACTERISTIC_ITEMWEIGHTS					"bots/bionicsonic_i.c"
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.5

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.3
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.15
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.6
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.2
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.4
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.3
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.55
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.5
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.5
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.2
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.3
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.5

	CHARACTERISTIC_FIRETHROTTLE					0.35
}

skill 4
{
	CHARACTERISTIC_NAME							"BionicSonic"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.7
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/bionicsonic_w.c"
	CHARACTERISTIC_AIM_SKILL					0.55
	CHARACTERISTIC_AIM_ACCURACY					0.7
	CHARACTERISTIC_VIEW_FACTOR					0.5
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					2

	CHARACTERISTIC_CHAT_FILE					"bots/bionicsonic_t.c"
	CHARACTERISTIC_CHAT_NAME					"bionicsonic"
	CHARACTERISTIC_CHAT_CPM						200
	CHARACTERISTIC_CHAT_INSULT					0.5
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.5
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.5

	CHARACTERISTIC_CROUCHER						0.2
	CHARACTERISTIC_JUMPER						0.4
	CHARACTERISTIC_WEAPONJUMPING				0.2
	CHARACTERISTIC_GRAPPLE_USER					0.5

	CHARACTERISTIC_ITEMWEIGHTS					"bots/bionicsonic_i.c"
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.5

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.3
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.15
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.6
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.2
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.4
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.3
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.55
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.5
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.5
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.2
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.3
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.5

	CHARACTERISTIC_FIRETHROTTLE					0.35
}

skill 5
{
	CHARACTERISTIC_NAME							"BionicSonic"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.7
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/bionicsonic_w.c"
	CHARACTERISTIC_AIM_SKILL					0.55
	CHARACTERISTIC_AIM_ACCURACY					0.7
	CHARACTERISTIC_VIEW_FACTOR					0.5
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					2

	CHARACTERISTIC_CHAT_FILE					"bots/bionicsonic_t.c"
	CHARACTERISTIC_CHAT_NAME					"bionicsonic"
	CHARACTERISTIC_CHAT_CPM						200
	CHARACTERISTIC_CHAT_INSULT					0.5
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.5
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.5

	CHARACTERISTIC_CROUCHER						0.2
	CHARACTERISTIC_JUMPER						0.4
	CHARACTERISTIC_WEAPONJUMPING				0.2
	CHARACTERISTIC_GRAPPLE_USER					0.5

	CHARACTERISTIC_ITEMWEIGHTS					"bots/bionicsonic_i.c"
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.5

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.3
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.15
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.6
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.2
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.4
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.3
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.55
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.5
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.5
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.2
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.3
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.5

	CHARACTERISTIC_FIRETHROTTLE					0.35
}
