//===========================================================================
//	Sonic	version 0.0
//
//
//	Made with doktor's BotStudio v. 0.98
//	http://www.planetquake.com/botstudio  e-mail: doktor@cutey.com
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"Sonic"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.5
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/sonic_w.c"
	CHARACTERISTIC_AIM_SKILL					0.5
	CHARACTERISTIC_AIM_ACCURACY					0.65
	CHARACTERISTIC_VIEW_FACTOR					0.7
	CHARACTERISTIC_VIEW_MAXCHANGE				220
	CHARACTERISTIC_REACTIONTIME					3.5

	CHARACTERISTIC_CHAT_FILE					"bots/sonic_t.c"
	CHARACTERISTIC_CHAT_NAME					"sonic"
	CHARACTERISTIC_CHAT_CPM						200
	CHARACTERISTIC_CHAT_INSULT					0.5
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.5
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.5

	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.5
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.5

	CHARACTERISTIC_ITEMWEIGHTS					"bots/sonic_i.c"
	CHARACTERISTIC_AGGRESSION					0.6
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.7

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.3
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.1
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.65
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.05
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.8
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.35
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.15
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.5
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.55
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.1
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.35
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.4

	CHARACTERISTIC_FIRETHROTTLE					0.75
}

skill 4
{
	CHARACTERISTIC_NAME							"Sonic"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/sonic_w.c"
	CHARACTERISTIC_AIM_SKILL					0.55
	CHARACTERISTIC_AIM_ACCURACY					0.65
	CHARACTERISTIC_VIEW_FACTOR					0.7
	CHARACTERISTIC_VIEW_MAXCHANGE				220
	CHARACTERISTIC_REACTIONTIME					3.5

	CHARACTERISTIC_CHAT_FILE					"bots/sonic_t.c"
	CHARACTERISTIC_CHAT_NAME					"sonic"
	CHARACTERISTIC_CHAT_CPM						200
	CHARACTERISTIC_CHAT_INSULT					0.5
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.5
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.5

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.5
	CHARACTERISTIC_WEAPONJUMPING				0.05
	CHARACTERISTIC_GRAPPLE_USER					0.5

	CHARACTERISTIC_ITEMWEIGHTS					"bots/sonic_i.c"
	CHARACTERISTIC_AGGRESSION					0.6
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.7

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.3
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.1
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.65
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.05
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.8
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.35
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.25
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.5
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.55
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.1
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.35
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.4

	CHARACTERISTIC_FIRETHROTTLE					0.75
}

skill 5
{
	CHARACTERISTIC_NAME							"Sonic"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.95
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/sonic_w.c"
	CHARACTERISTIC_AIM_SKILL					0.6
	CHARACTERISTIC_AIM_ACCURACY					0.65
	CHARACTERISTIC_VIEW_FACTOR					0.7
	CHARACTERISTIC_VIEW_MAXCHANGE				220
	CHARACTERISTIC_REACTIONTIME					3.5

	CHARACTERISTIC_CHAT_FILE					"bots/sonic_t.c"
	CHARACTERISTIC_CHAT_NAME					"sonic"
	CHARACTERISTIC_CHAT_CPM						200
	CHARACTERISTIC_CHAT_INSULT					0.5
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.5
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.5

	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.5
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.5

	CHARACTERISTIC_ITEMWEIGHTS					"bots/sonic_i.c"
	CHARACTERISTIC_AGGRESSION					0.6
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.7

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.3
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.1
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.65
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.05
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.8
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.35
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.25
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.5
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.55
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.1
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.35
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.4

	CHARACTERISTIC_FIRETHROTTLE					0.75
}
